global:
  scrape_interval: 15s

scrape_configs:
  - job_name: auth-service
    static_configs:
      - targets: ["auth-service:8000"]
  - job_name: user-profile-service
    static_configs:
      - targets: ["user-profile-service:8000"]
  - job_name: weather-service
    static_configs:
      - targets: ["weather-service:8000"]
  - job_name: market-service
    static_configs:
      - targets: ["market-service:8000"]
  - job_name: agent-service
    static_configs:
      - targets: ["agent-service:8000"]
  - job_name: notification-service
    static_configs:
      - targets: ["notification-service:8000"]
