# Frontend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: sroa
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: 815210276744.dkr.ecr.eu-west-1.amazonaws.com/sroa-frontend:da5a259a14eb449f57d4decf27412fbcafcb3ce0
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: sroa-config
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
---
# Frontend Service
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: sroa
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app: frontend
