# Defines the storage type for AWS EBS volumes
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sroa-storage
# Specifies that we are using AWS Elastic Block Store
provisioner: kubernetes.io/aws-ebs
parameters:
  # gp3 is the latest generation of general-purpose SSD volumes
  type: gp3
# 'Retain' ensures that the underlying AWS volume is NOT deleted if the K8s resource is deleted
reclaimPolicy: Retain
# Allows expanding the volume size later without downtime
allowVolumeExpansion: true
# Ensures the volume is created in the same Availability Zone where the Pod is scheduled
volumeBindingMode: WaitForFirstConsumer
