{{- $root := . -}}
{{- range $service := .Values.services }}
{{- if $service.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sroa.fullname" $root }}-{{ $service.name }}
spec:
  replicas: {{ $service.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "sroa.fullname" $root }}-{{ $service.name }}
  template:
    metadata:
      labels:
        app: {{ include "sroa.fullname" $root }}-{{ $service.name }}
    spec:
      containers:
        - name: {{ $service.name }}
          image: "{{ $service.image.repository }}:{{ $service.image.tag }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - containerPort: {{ $service.service.port }}
          env:
{{- range $key, $value := $service.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
{{- end }}
          resources:
{{ toYaml $service.resources | indent 12 }}
---
{{- end }}
{{- end }}
