{{- $root := . -}}
{{- range $service := .Values.services }}
{{- if $service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sroa.fullname" $root }}-{{ $service.name }}
spec:
  type: {{ $service.service.type }}
  selector:
    app: {{ include "sroa.fullname" $root }}-{{ $service.name }}
  ports:
    - port: {{ $service.service.port }}
      targetPort: {{ $service.service.port }}
---
{{- end }}
{{- end }}
