name: Reusable deployment email notification

on:
  workflow_call:
    inputs:
      recipient:
        required: true
        type: string
      subject:
        required: true
        type: string
      message:
        required: true
        type: string
      from:
        required: true
        type: string

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send deployment notification email
        uses: dawidd6/action-send-mail@v4
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.GMAIL_SMTP_USERNAME }}
          password: ${{ secrets.GMAIL_SMTP_PASSWORD }}
          subject: ${{ inputs.subject }}
          body: ${{ inputs.message }}
          to: ${{ inputs.recipient }}
          from: ${{ inputs.from }}
          secure: false
