name: "Stage 6: GitOps Bridge"
on:
  workflow_call:
    inputs:
      image_tag:
        required: true
        type: string
      branch:
        required: true
        type: string

jobs:
  update-manifests:
    runs-on: ubuntu-latest
    # Production Rule: Bot ko repository mein push karne ki permission deni hogi
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ inputs.branch }}

      - name: Update Manifests with New Image Tag
        run: |
          # Sabhi files mein 'latest' tag ko naye Commit SHA se replace karein
          sed -i "s/latest/${{ inputs.image_tag }}/g" infra/k8s/backend/resources.yaml
          sed -i "s/latest/${{ inputs.image_tag }}/g" infra/k8s/frontend/resources.yaml

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore: deploy version ${{ inputs.image_tag }} [skip ci]" || echo "No changes to commit"
          git push origin ${{ inputs.branch }}
