name: "Stage 3a: Hadolint"
on:
  workflow_call:
    inputs:
      dockerfile_path:
        required: true
        type: string
jobs:
  hadolint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Dockerfile Linting
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ${{ inputs.dockerfile_path }}
          ignore: DL3008
